### ISSUE TITLE
Merging this with fluent-plugin-geoip

### ISSUE THREAD

**Issue by kiyoto** [mosuka/fluent-plugin-filter-geoip#1]
As you probably know, there's already @y-ken's plugin for GeoIP output. Here is the relevant issue: https://github.com/y-ken/fluent-plugin-geoip/issues/17

What do you think about rolling this plugin into that repo? While I really, really appreciate your participation, it's much easier for users if there is a single "go-to" plugin for GeoIP =)

**Comment by mosuka** [comment]
Hi @kiyoto,
I also agree with your opinion.
I made this filter-plugin to support GeoIP2 as a prototype. However @y-ken's plugin is not supported in GeoIP2.
What is the meaning of "rolling this plugin into that repo"? Is there anything that I can do? :)
